### ISSUE TITLE
New Ideas for Superevents 

### ISSUE THREAD

**Issue by LapdCode3** [SuperPyroManiac/SuperEvents#1]
public shootout guys firing at anyone (keep weapons simple pistol shotgun or carbine rifle 

street fight in public

disturbing the peace
(someones parked a party bus in middle of the road playing loud music near a quiet neighborhood)

drug dealer handing out drugs - be creative on the guys dealing and buying and location spots in strawberry and vinewwod area

Police Pursuit of a reckless driver - we can use it to interact with the lspdfr pursuit manager

anyways these are new ideas some never been done some need to be done for 0.4.3 
if these are created please give credit for the ideas 

thank you LapdCode3

**Comment by SuperPyroManiac** [comment]
Public shootout is already in progress for 1.1
Street fight, this sounds like the Fight event I already have in the plugin.
Drug dealer, this is planned for a future release.
Pursuit, will be in 1.1 as well.

Thanks for the ideas. Updates will be posted here following progress.

**Comment by NopeByeLSPDFR** [comment]
- Emergency Vehicles Responding: This would include Fire/EMS/Police responding to a callout.

**Comment by NopeByeLSPDFR** [comment]
Will add more to the list once I think of more.

**Comment by SuperPyroManiac** [comment]
@NopeByeLSPDFR Please create new issues for new ideas. Helps me keep track of them. I created one for you here: https://github.com/SuperPyroManiac/SuperEvents/issues/3
