### ISSUE TITLE
Event Suggestion - Emergency Vehicles Responding

### ISSUE THREAD

**Issue by SuperPyroManiac** [SuperPyroManiac/SuperEvents#3]
> NopeByeLSPDFR -
> Emergency Vehicles Responding: This would include Fire/EMS/Police responding to a callout.

**Comment by NopeByeLSPDFR** [comment]
- Store Robbery: A man/group runs into a store nearby and holds it up.
- Mugging: Someone in a less populated spot being mugged.
-Gang War: Maybe to do with the Vagos, Ballas and Families having gang wars.
-Stolen Vehicle: Someone runs up and steals a vehicle.
-Road Rage: Can be two drivers who are ramming each other or someone who is beating someone elses car.
-Tresspassing: Someone is tresspassing in e.g. a construction sight and is fighting with security or something along those lines.
They are some me and my friends thought would be fun to see.

**Comment by SuperPyroManiac** [comment]
Complete with the ideas I wanted to add. May add the stolen vehicle event in a future version. Thanks for the ideas!
